package(
    features = ["-swift.bundled_xctests"],
)
load("@build_bazel_rules_swift//swift:swift.bzl", "swift_test")

swift_test(
    name = "NonCocoaTests",
    srcs = [
        "SimpleTest.swift",
        "main.swift",
    ],
)