load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "User",
    srcs = ["User.swift"],
    deps = [
        "//ios-app/ThirdParty:ObjectMapper",
        "//ios-app/ThirdParty:RealmSwift",
    ]
)